name: set_env_on_push_main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: set_env
        run: |
            echo $RESEND_API_KEY 
        env:
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
     
      
        
